name: embedding_eeg_2022
channels:
- default
dependencies:
- python>=3.6
- ipython
- pip
- numpy
- matplotlib
- seaborn
- pandas
- scikit-learn
- h5py
- tqdm
- pytorch
- torchvision
- torchmetrics
- skorch
- umap-learn
- jupyterlab
- pip:
  - mne
  - git+https://github.com/PierreGtch/moabb.git@prepare_and_save_models#egg=moabb
  - pytorch-lightning
